### PR TITLE
Utility to load topography

### PR DESCRIPTION
**Pull request by gmaze**
Being to able to easily load local topography will be very useful for plotting or QC methods.
This PR will provide a new method to do this.

New API:
```python
    from argopy import TopoFetcher
    box = [-75, -45, 20, 30]
    ds = TopoFetcher(box).to_xarray()
```

This will help for https://github.com/euroargodev/terrain-following/issues/1

### CODE REVIEW

**Comment by ocefpaf** [comment]
I have a similar prototype for a stand alone package for this (but I was using etopo2 instead). Do you think it would be better to factor it out in its own pkd so other packages can depend on it?

The downside is a slower development pace and higher maintenance cost.

**Comment by gmaze** [comment]
> Do you think it would be better to factor it out in its own pkd so other packages can depend on it?

In theory, I would agree
In practice this would lead to another dependency to manage and sustain
So I would promote the idea of a simple function/method to be easily/freely copied/pasted from one library to the other

**Comment by ocefpaf** [comment]
To be honest I was on the fence and that is why I never published my version :-)

Sounds like a good plan!

**Review by gmaze — COMMENTED** [review]
"I am @gmaze and I approve this message"

**Pull request merged**
