### PR TITLE
Implement a GDAC ftp fetcher

### PR DESCRIPTION
**Pull request by gmaze**
Well, simply add a long time required GDAC ftp fetcher

This PR has many commits because implementing the GDAC ftp fetcher required a full new index store (based on #113 ) and a new pytest design.

But the new pytest design was very very slow, so I had to redesign CI tests as well 😭

### CODE REVIEW

**Comment by gmaze** [comment]
This PR is on hold because I tried to implement a new design for CI tests but it fails on GA while it works from home and I can't figure why this is happening !

**Comment by gmaze** [comment]
I think we're ready for review here 🍿 

New API documented in here:
https://argopy.readthedocs.io/en/gdac-ftp-fetcher/whats-new.html
https://argopy.readthedocs.io/en/gdac-ftp-fetcher/data_sources.html

and new store details:
https://argopy.readthedocs.io/en/gdac-ftp-fetcher/generated/argopy.stores.ftpstore.html#argopy.stores.ftpstore
https://argopy.readthedocs.io/en/gdac-ftp-fetcher/generated/argopy.stores.argo_index_pa.indexstore_pyarrow.html#argopy.stores.argo_index_pa.indexstore_pyarrow
https://argopy.readthedocs.io/en/gdac-ftp-fetcher/generated/argopy.stores.argo_index_pd.indexstore_pandas.html#argopy.stores.argo_index_pd.indexstore_pandas

**Comment by gmaze** [comment]
Hopefully we're finally good 👍🏻  to go

The new data fetcher API:
```python
from argopy import DataFetcher
argo = DataFetcher(src='gdac')
argo = DataFetcher(src='gdac', ftp="https://data-argo.ifremer.fr")  # http server, the default and fastest !
argo = DataFetcher(src='gdac', ftp="ftp://ftp.ifremer.fr/ifremer/argo")  # works with ftp
argo = DataFetcher(src='gdac', ftp=argopy.tutorial.open_dataset("localftp")[0]) # or with local GDAC folder
```

works also with the IndexFetcher

The new fetcher can return the index without downloading the data:
```python
argo = DataFetcher(src='gdac').float(6903076)
argo.index
```

This relies on the new index store:
```python
from argopy.stores.argo_index_pa import indexstore_pyarrow as indexstore
# or if you don't have/want pyarrow:
# from argopy.stores.argo_index_pd import indexstore_pandas as indexstore

idx = indexstore(host="https://data-argo.ifremer.fr", index_file="ar_index_global_prof.txt")  # Default
idx.load()
idx.search_lat_lon_tim([-60, -55, 40., 45., '2007-08-01', '2007-09-01'])
idx.N_MATCH  # Return number of search results
idx.to_dataframe()  # Convert search results to a dataframe
```

**Review by quai20 — APPROVED** [review]
:+1:

**Pull request merged**
