### PR TITLE
S3 support

### PR DESCRIPTION
**Pull request by gmaze**
The Argo ADMT is experiencing with Amazon S3 in order to move the GDAC infrastructure into the cloud.
In order to prepare argopy for this and to be able to [access and test the AWS prototype server](https://github.com/OneArgo/ADMT/issues/5), we need to develop support for S3.
This would require:
- [x] New file store to support [S3 with fsspec](https://filesystem-spec.readthedocs.io/en/latest/api.html#other-known-implementations), this is based on [s3fs](https://s3fs.readthedocs.io/en/latest/)
- [x] Update Index store to support S3

A new data fetcher shall be developed in another PR

### CODE REVIEW

**Comment by gmaze** [comment]
@tcarval is there any reasons for not having the gz index files on s3 ? 
https://argo-gdac-sandbox.s3.eu-west-3.amazonaws.com/pub/index.html#pub/idx/

**Comment by tcarval** [comment]
> @tcarval is there any reasons for not having the gz index files on s3 ? https://argo-gdac-sandbox.s3.eu-west-3.amazonaws.com/pub/index.html#pub/idx/

I will add the gz indexes

**Comment by gmaze** [comment]
New IndexStore ready to work with AWS S3 core index file

```python
from argopy import ArgoIndex
idx = ArgoIndex(host='s3://argo-gdac-sandbox/pub/idx').load()
idx.search_wmo_cyc(6903091, 1)
```

**Comment by gmaze** [comment]
there's an issue I can't manage to solve, I need help

On github actions, when unit testing the new s3 store, we fall back on an anonymous requests with the following client:
```
import boto3
from botocore import UNSIGNED
from botocore.client import Config

fs = boto3.client('s3', config=Config(signature_version=UNSIGNED))
```

but tests fails with the error:
```
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the SelectObjectContent operation: Access Denied
```

I don't get why we can't access the object anonymously

@tcarval could you please double check the bucket access policy to make sure that it can be accessed anonymously

poke: @quai20

**Comment by gmaze** [comment]
Looking for a solution on the test repo here: https://github.com/gmaze/ga_aws_access

**Pull request merged**
