### PR TITLE
Adding Argovis to Argopy data sources

### PR DESCRIPTION
**Pull request by tylertucker202**
Argo data fetcher for Argovis.
Code borrows heavily from API gathered [here](https://github.com/earthcube2020/ec20_tucker_etal/blob/master/EC2020_argovis_python_api.ipynb)
This is comprised of functions used to query Argovis API
query functions either return dictionary objects or error messages.

Work on how to integrate these functions within Argopy's language remains to be made. I'm afraid I don't understand the OOP design behind the data fetcher classes...

Also included is a base case for testing made from asserts.

### CODE REVIEW

**Comment by gmaze** [comment]
Hi @tylertucker202 
This is a good start, great !

Below is a more precise guideline to have your fetcher compliant with our API facade and overall internal design of argopy. 
I acknowledge that this guideline may look enormous, but this is mainly some re-organization and few developments to your code.
This guideline should come in the [documentation](https://argopy.readthedocs.io/en/latest/contributing.html#data-fetchers).

So, a new data fetcher must comply with:

## Inheritance
- [ ] Inherit from the ``ArgoDataFetcherProto`` under argopy.data_fetchers/proto.py
This enforces minimal internal design compliance.

## Auto-discovery for the facade

### Fetcher properties
- [ ] The new fetcher must come with the ``access_points``, ``exit_formats`` and ``dataset_ids`` properties at the top of the file, e.g.:
```
access_points = ['wmo' ,'box']
exit_formats = ['xarray']
dataset_ids = ['phy', 'bgc']  # First is default
```
Values depend on what argovis can return and what you want to implement. A good start is with the ``wmo`` access point and the ``phy`` dataset_ids. The ``xarray`` data format is the minimum required, but I see you internally work with Pandas dataframe, so you can add ``dataframe`` as well.
These variables are used by the facade to auto-discover the fetcher capabilities. 
The ``dataset_ids`` property is used to determine which variables can be retrieved.

### Fetcher access points
- [ ] The new fetcher must come at least with a ``Fetch_wmo`` or ``Fetch_wmo`` class, basically one for each of the ``access_points`` listed as properties. 
More generaly we may have a main class that provides the key functionalities to retrieve data from the source, and then classes for each of the ``access_points`` of your fetcher. This pattern could look like this:
```
class ArgovisDataFetcher(ArgoDataFetcherProto)
class Fetch_wmo(ArgovisDataFetcher)
class Fetch_box(ArgovisDataFetcher)
```
It could also be like:
```
class Fetch_wmo(ArgoDataFetcherProto)
class Fetch_box(ArgoDataFetcherProto)
```
Note that the class names `Fetch_wmo` and `Fetch_box` must not change, this is also used by the facade to auto-discover the fetcher capabilities. 

**Fetch_wmo** is used to retrieve platforms and eventually profiles data. It must take in the ``__init__()`` method a ``WMO`` and a ``CYC`` as first and second options. ``WMO`` is always passed, ``CYC`` is optional.
These are passed by the facade to implement the ``fetcher.float`` and ``fetcher.profile`` methods.
When a float (or platform as you call it in argovis) is requested, the ``CYC`` option is not passed by the facade.
Last, ``WMO`` and ``CYC`` are ether a single integer or a list of integers: this means that ``Fetch_wmo`` must be able to handle more than one float/platform retrieval.

**Fetch_box** is used to retrieve a rectangular domain in space and time. It must take in the ``__init__()`` method a ``BOX`` as first option that is passed a list(lon_min: float, lon_max: float, lat_min: float, lat_max: float, pres_min: float, pres_max: float, date_min: str, date_max: str) from the facade. The two bounding dates [date_min and date_max] should be optional (if not specified, the entire time series is requested by the user).

## File systems
- [ ] All your http requests should go through the internal ``httpstore``, an internal wrapper around fsspec that allows to manage request caching very easily. You can simply use it this way for json requests:
```python
from argopy.stores import httpstore
with httpstore(timeout=120).open("https://argovis.colorado.edu/catalog/profiles/5904797_12") as of:
    profile = json.load(of)
```
This should replace your ``urlopenjson`` method.

## Output data format
- [ ] Last but not least, about the output data. In **argopy**, we want to provide data for both expert and standard users. This is explained and illustrated in the [documentation here](https://argopy.readthedocs.io/en/latest/user_mode.html). This means for the argovis data fetcher that the argovis json content should be curated and clean of any internal/jargon variables that is not part of the Argo ADMT vocabulary. For instance, I have spotted variables like: ``bgcMeasKeys`` or ``geoLocation``. This will ensure that whatever the data source used by users, the output xarray or dataframe will be formatted and contain the same variables. This will also ensure that other argopy features can be used on the argovis output, like plotting or xarray data manipulation.

**Comment by gmaze** [comment]
I recognized this may look like a lot of work, but I can help !

**Comment by tylertucker202** [comment]
Thanks for the support and feedback. I have carefully read the requirements provided. The problem is doable, but the scope is somewhat beyond what I expected.

Is there a way we can start small? It was my impression that I wouldn't have to understand how data fetchers work in order to implement a simple profile query.

Can we break this up into digestible tasks? It can be something as simple as getting the JSON data from one profile.
```
profile = ArgoDataFetcher(src='argovis').profile(6902746, 34)
```

From there we can loop over cycle numbers to return multiple profiles, etc. I can piece together the .profile() method, but the ArgoDataFetcher is where I'm lost. Can you provide a starting point for initializing ArgoDataFetcher with 'argovis' as a source?

Thank you for understanding my reluctance to work on this without more help.

**Comment by gmaze** [comment]
hi @tylertucker202 
I understand, no worries, and I'm here to help.
I think the most tricky part is to make sure that data returned by the argovis fetcher are somehow "compatible" with what is returned by the other fetchers.
So the 1st task I believe is at the fetcher level on this point, otherwise I will provide a mockup of the fetcher that is otherwise compatible with the argopy internal machinery and highlight where we need your input, is that ok with you ?

**Comment by gmaze** [comment]
@tylertucker202 
This should get you started, I inserted 2 lines where we need your input:

```python
from argopy.data_fetchers.proto import ArgoDataFetcherProto
from argopy.stores import httpstore
import json
from abc import ABC, abstractmethod
from argopy.utilities import list_standard_variables

class ArgovisDataFetcher(ArgoDataFetcherProto):
    ###
    # Methods to be customised for a specific Argovis request
    ###
    @abstractmethod
    def init(self):
        """ Initialisation for a specific fetcher """
        pass
    
    @abstractmethod
    def cname(self):
        """ Return a unique string defining the request

            Provide this string to populate meta data and titles
        """
        pass
    
    @property
    def url(self):
        """ Return the URL used to download data """
        pass
    ###
    # Methods that must not change
    ###
    def __init__(self,
             ds: str = "",
             cache: bool = False,
             cachedir: str = "",
             **kwargs):
        """ Instantiate an Argovis Argo data loader

            Parameters
            ----------
            ds: 'phy' or 'bgc' # @tylertucker202: Do you provide BGC data as well ?? what is the way to select which data (core or bgc) to retrieve ?
            cache : False
            cachedir : None
        """
        self.fs = httpstore(cache=cache, cachedir=cachedir, timeout=120)
        self.definition = 'Argovis Argo data fetcher'
        self.dataset_id = OPTIONS['dataset'] if ds == '' else ds
        self.init(**kwargs)
    
    def __repr__(self):
        summary = ["<datafetcher '%s'>" % self.definition]
        summary.append("Domain: %s" % self.cname())
        return '\n'.join(summary)

    # This one will be delegated to the httpstore later
    def open_json(self, url):
        return self.fs.open(url)

    def json2dataframe(self, profiles):
        """ convert json data to Pandas DataFrame """
        # Make sure we deal with a list
        if isinstance(profiles, list):
            data = profiles
        else: 
            data = [profiles] 
        # Transform
        rows = []
        for profile in data:
            keys = [ x for x in profile.keys() if not x in ['measurements', 'bgcMeas']]
            meta_row = dict( (key, profile[key]) for key in keys)
            for row in profile['measurements']:
                row.update(meta_row)
                rows.append(row)
        df = pd.DataFrame(rows)
        return df
    
    def filter_data_mode(self, ds, **kwargs):
        ds = ds.argo.filter_data_mode(errors='ignore', **kwargs)
        if ds.argo._type == 'point':
            ds['N_POINTS'] = np.arange(0, len(ds['N_POINTS']))
        return ds

    def filter_qc(self, ds, **kwargs):
        ds = ds.argo.filter_qc(**kwargs)
        if ds.argo._type == 'point':
            ds['N_POINTS'] = np.arange(0, len(ds['N_POINTS']))
        return ds

    def filter_variables(self, ds, mode='standard'):
        if mode == 'standard':
            to_remove = sorted(list(set(list(ds.data_vars)) - set(list_standard_variables())))
            return ds.drop_vars(to_remove)
        else:
            return ds

class Fetch_wmo(ArgovisDataFetcher):
    def init(self, WMO=[], CYC=None):
        """ Create Argo data loader for WMOs and CYCs

            Parameters
            ----------
            WMO : list(int)
                The list of WMOs to load all Argo data for.
            CYC : int, np.array(int), list(int)
                The cycle numbers to load.
        """
        if isinstance(WMO, int):
            WMO = [WMO]  # Make sure we deal with a list
        if isinstance(CYC, int):
            CYC = np.array((CYC,), dtype='int')  # Make sure we deal with an array of integers
        if isinstance(CYC, list):
            CYC = np.array(CYC, dtype='int')  # Make sure we deal with an array of integers
        self.WMO = WMO
        self.CYC = CYC

        self.definition = "?"
        if self.dataset_id == 'phy':
            self.definition = 'Argovis Argo data fetcher for profiles'
        return self
    
    def cname(self):
        """ Return a unique string defining the constraints """
        if len(self.WMO) > 1:
            listname = ["WMO%i" % i for i in self.WMO]
            if isinstance(self.CYC, (np.ndarray)):
                [listname.append("CYC%0.4d" % i) for i in self.CYC]
            listname = ";".join(listname)
        else:
            listname = "WMO%i" % self.WMO[0]
            if isinstance(self.CYC, (np.ndarray)):
                listname = [listname]
                [listname.append("CYC%0.4d" % i) for i in self.CYC]
                listname = "_".join(listname)
        listname = self.dataset_id + "_" + listname
        return listname

    @property
    def url(self):
        """ Return the URL used to download data """
        urls = []
        if isinstance(self.CYC, (np.ndarray)) and self.CYC.nbytes > 0:
            for wmo in self.WMO:
                for cyc in self.CYC:
                    profile_number = str(wmo) + '_' + str(cyc)
                    urls.append('https://argovis.colorado.edu/catalog/profiles/{}'.format(profile_number))
        else:
            for wmo in self.WMO:
                urls.append('https://argovis.colorado.edu/catalog/platforms/{}'.format(str(wmo)))
        return urls
    
    def to_xarray(self):
        """ Download and return data as xarray Datasets """
        results = []
        for url in self.url:
            with self.open_json(url) as of:
                js = json.load(of)
                ds = self.json2dataframe(js).to_xarray()
                # @tylertucker202: This is where we would rename variables, cast data types, etc to ensure upper level compatibility with argopy fetcher facade.
                ds = ds.rename({'index': 'N_POINTS'}) # For instance !
                results.append(ds)
        results = [r for r in results if r is not None]  # Only keep non-empty results
        if len(results) > 0:
            ds = xr.concat(results, dim='N_POINTS', data_vars='all', coords='all', compat='override')
            ds['N_POINTS'] = np.arange(0, len(ds['N_POINTS']))  # Re-index to avoid duplicate values
            ds = ds.set_coords('N_POINTS')
            ds = ds.sortby('date')
            return ds
        else:
            raise ValueError("CAN'T FETCH ANY DATA !")

# different ways to use (internally):
fetcher = Fetch_wmo(cache=0, cachedir="./tmp", WMO=6901929)
fetcher = Fetch_wmo(cache=0, cachedir="./tmp", WMO=6901929, CYC=12)
fetcher = Fetch_wmo(cache=0, cachedir="./tmp", WMO=6901929, CYC=[1, 12])
fetcher = Fetch_wmo(cache=0, cachedir="./tmp", WMO=[6901929, 2901623])
fetcher = Fetch_wmo(cache=0, cachedir="./tmp", WMO=[6901929, 2901623], CYC=12)
fetcher = Fetch_wmo(cache=0, cachedir="./tmp", WMO=[6901929, 2901623], CYC=[1, 12])

fetcher = Fetch_wmo(WMO=6901929)
fetcher = Fetch_wmo(WMO=6901929, CYC=12)
fetcher = Fetch_wmo(WMO=6901929, CYC=[1, 12])
fetcher = Fetch_wmo(WMO=[6901929, 2901623])
fetcher = Fetch_wmo(WMO=[6901929, 2901623], CYC=12)
fetcher = Fetch_wmo(WMO=[6901929, 2901623], CYC=[1, 12])

print(fetcher)
print(fetcher.url)
ds = fetcher.to_xarray()
np.unique(ds['_id'])
# fetcher.fs.clear_cache()
```

**Comment by tylertucker202** [comment]
Thank you for your support and guidance. I'm taking a bite out of this task and am having trouble loading the libraries. 

After creating a virtual environment (using anaconda distro) and installing the libraries specified in requirements.txt I get the error

`ModuleNotFoundError: No module named 'argopy.stores'`

This fixes the error

`import sys
sys.path.append('../stores')
from fsspec_wrappers.py import httpstore
`

But then get the loading error
`
ImportError: cannot import name 'FileSystemHasNoCache'
` 

Not sure what is going on here, but httpstore is not able to load. For now, I'll revert to simple requests library so that I can rename variables and cast data types.

**Comment by tylertucker202** [comment]
Alright, we have something now! The data fetcher is able to convert JSON into dataframes and xarray with the standard user mode conventions. A few caveats:

- The database we are using stores 32-bit floats as 64-bit doubles. We can change them back to 32 bit if necessary.
- Did not add measurement qcs. TEMP_QC, PRES_QC, PSAL_QC are all 1 for Argovis. We can perform some additional logic that includes an array of 1s for that variable.
- httpstore isn't loading. I couldn't even get the unit tests to work on my end. Not sure why so I replaced it with my own requests library api call. 
- Our BGC API calls will need some more discussion. They are limited to either single profiles at a time, or for platform calls that only allow 2 parameters at a time. This was to get around performance issues when querying huge amounts of data at once. The database has a cap of 16 MB of data queried at a time. Some floats have a lot more BGC data hence we had to retrieve subsets of the data. [See the following API call](https://argovis.colorado.edu/catalog/bgc_platform_data/5906243?yaxis=pres&xaxis=doxy). We were asked to keep the QC values for these parameters. It is not impossible to retrieve BGC, but will need further refinement.
- converting to_xarray() is getting an out of memory error for float queries converting from data frames.

See [here](https://github.com/tylertucker202/argopy/blob/argovis/argopy/data_fetchers/ArgovisDataFetcherScratch.ipynb) for a Jupyter notebook implements a modified version of ArgovisDataFetcher.

Its a pleasure to have made progress on this item. Thanks for your help!

**Comment by gmaze** [comment]
> Thank you for your support and guidance. I'm taking a bite out of this task and am having trouble loading the libraries.
> 
> After creating a virtual environment (using anaconda distro) and installing the libraries specified in requirements.txt I get the error
> 
> `ModuleNotFoundError: No module named 'argopy.stores'`
> 
> This fixes the error
> 
> `import sys sys.path.append('../stores') from fsspec_wrappers.py import httpstore `
> 
> But then get the loading error
> `ImportError: cannot import name 'FileSystemHasNoCache'`
> 
> Not sure what is going on here, but httpstore is not able to load. For now, I'll revert to simple requests library so that I can rename variables and cast data types.

Do you use the last master version ?

Here is how I usually set-up my notebook for dev:

```python
import sys, os, glob
import numpy as np
import pandas as pd
import xarray as xr
xr.set_options(display_style="text");

# Importing argopy in dev mode:
sys.path.insert(0, "/Users/gmaze/git/github/euroargodev/argopy")
import git
import argopy
from argopy.options import OPTIONS
# argopy.set_options(local_ftp='/Volumes/Data/ARGO')
# argopy.set_options(mode='expert')
print("argopy:", argopy.__version__, 
      "\nsrc:", argopy.__file__, 
      "\nbranch:", git.Repo(search_parent_directories=True).active_branch.name, 
      "\noptions:", OPTIONS)

from argopy import DataFetcher as ArgoDataFetcher
from argopy import IndexFetcher as ArgoIndexFetcher
argopy.clear_cache()

# For argovis fetcher dev:
from argopy.stores import httpstore

# For plots:
import matplotlib.pyplot as plt
import matplotlib as mpl
import cmocean
```

**Comment by gmaze** [comment]
> Alright, we have something now! The data fetcher is able to convert JSON into dataframes and xarray with the standard user mode conventions. A few caveats:
> 
>     * The database we are using stores 32-bit floats as 64-bit doubles. We can change them back to 32 bit if necessary.
> 
>     * Did not add measurement qcs. TEMP_QC, PRES_QC, PSAL_QC are all 1 for Argovis. We can perform some additional logic that includes an array of 1s for that variable.
> 
>     * httpstore isn't loading. I couldn't even get the unit tests to work on my end. Not sure why so I replaced it with my own requests library api call.
> 
>     * Our BGC API calls will need some more discussion. They are limited to either single profiles at a time, or for platform calls that only allow 2 parameters at a time. This was to get around performance issues when querying huge amounts of data at once. The database has a cap of 16 MB of data queried at a time. Some floats have a lot more BGC data hence we had to retrieve subsets of the data. [See the following API call](https://argovis.colorado.edu/catalog/bgc_platform_data/5906243?yaxis=pres&xaxis=doxy). We were asked to keep the QC values for these parameters. It is not impossible to retrieve BGC, but will need further refinement.
> 
>     * converting to_xarray() is getting an out of memory error for float queries converting from data frames.
> 
> 
> See [here](https://github.com/tylertucker202/argopy/blob/argovis/argopy/data_fetchers/ArgovisDataFetcherScratch.ipynb) for a Jupyter notebook implements a modified version of ArgovisDataFetcher.
> 
> Its a pleasure to have made progress on this item. Thanks for your help!

Great !

- If argovis only works with QC=1 data, then it will be limited to the `standard` user mode.
- convert 32 to 64 is not mandatory, I think that's ok at this point. Is it the origin of the xarray memory error ?
- httpstore isn't loading: this is merely an environment issue, the fetcher will come into the library and this should fix it
- About BGC data: argopy is not ready yet to provide BGC data, this would need more work and thinking to be consistent throughout the fetchers, so it's ok if we don't support BGC retrieval yet
- I never encountered the memory error you've got, I will look into that

**Comment by gmaze** [comment]
By the way @tylertucker202 , your notebook at https://github.com/earthcube2020/ec20_tucker_etal/blob/master/EC2020_argovis_python_api.ipynb is great.
I foresee a lot of simplification to reach nearly the same result if only  data were fetched through the argopy / argovis fetcher !

**Comment by gmaze** [comment]
Hi @tylertucker202 
I'm working on this
I pushed some commits to merge back the master (last release 0.1.4)
And started to update the fetcher to better integrate internally
So far, it seems to work:
```
ArgoDataFetcher(src='argovis').profile(6901929, 1).to_xarray()
```
But I don't have the same number of points compared to the erddap fetcher, so we need to better identify the differences

**Comment by gmaze** [comment]
We now also have:
```python
ArgoDataFetcher(src='argovis', cache=0).float(6901929).to_xarray()
```
working

**Comment by gmaze** [comment]
We still need to implement the "region" access point !

**Comment by tylertucker202** [comment]
Excellent progress! I can work on the region class today. Do we want to allow only rectangles or allow polygons?

**Comment by gmaze** [comment]
It's almost done, I'm on it
For this 1st version, we should keep the rectangle only for API compatibility with the other fetchers.
BUT this is an awesome feature of Argovis, so we will have it at some point.

By the way, you limit fetching to no more than 3 months, but we could have small domain and large time range for quite a small amount of data, would it be possible to release that constrain ?

**Comment by tylertucker202** [comment]
Thanks for pushing these changes by the way. We are still having some snags loading the argopy library. Sorry that I can't seem to get it working. 

I tried importing this a few different ways, but no luck. I'll have to be creative on how I develop the box selector class today. We shall persevere. 

FYI, I'm see that we are pushing to the master branch? I was adding the class to the argovis branch of my fork. I'll push to the master going forward, just wanted to let you know where the work is getting stored.

**Comment by gmaze** [comment]
@tylertucker202 

> Thanks for pushing these changes by the way. We are still having some snags loading the argopy library. Sorry that I can't seem to get it working.
> I tried importing this a few different ways, but no luck. I'll have to be creative on how I develop the box selector class today. We shall persevere.

I am already working on the box selector, it's done !
I am polishing the code to make it more robust to errors

By the way, why do you throw an http 304 error when the request does not provide any results ? Basically, when we request:
[https://argovis.colorado.edu/catalog/platforms/12](https://argovis.colorado.edu/catalog/platforms/12)
The response code is 304, but should we expect a 404 ?

> FYI, I'm see that we are pushing to the master branch? I was adding the class to the argovis branch of my fork. I'll push to the master going forward, just wanted to let you know where the work is getting stored.
Yeah, I wasn't sure where I was pushing my work ! Then I realized it was going to your fork/master. 
I didn't understood why it went there
Anyway, your fork needed to be merged with v0.1.4 from my master

**Comment by gmaze** [comment]
Awesome !
Screenshot 2020-06-25 at 22 41 44

**Comment by gmaze** [comment]
@tylertucker202 ,  
This is ready to merge for me ! 
Everything looks good so far

@tylertucker202 do you confirm ?

@quai20, can you please review this ?

Key changes:
- New data fetcher at argopy.data_fetchers.argovis, named "argovis" for the facade
- Small refactoring of the DataFetcherPrototype (now include ``_format``)
- New method to load json files with the httpstore
- Unit testing updated to include the new fetcher (although still need more tests)
- Removed default box definition to the erddap and localftp fetcher
- Update list_available_index_src() to test for argovis fetcher

**Comment by tylertucker202** [comment]
> By the way, why do you throw an http 304 error when the request does not provide any results ? Basically, when we request:
> https://argovis.colorado.edu/catalog/platforms/12
> The response code is 304, but should we expect a 404 ?

@gmaze, I'm not sure why the actual error code thrown is 303. The intention of this error is to let the user know that the platform with a WMO number of 12 is not in the database. The Express.js server that interfaces with the database 303 seems to set this error code a default. I'll need to find a more appropriate error code. 404 can be an option.

**Comment by quai20** [comment]
> 
> @quai20, can you please review this ?
> 
I'll do my best this morning !

**Comment by gmaze** [comment]
>     * in `options.py`, don't we have to add 'argovis' to `_DATA_SOURCE_LIST` ?

Well spotted !
Fixed

**Comment by gmaze** [comment]
* **argovis** fetching works for `float`, `profile` and `region`. Region fetching doesn't return the DIRECTION variable though. That makes `ds.argo.point2profile()` failed

I think this is coming from Argovis response,
 @tylertucker202 , for this kind of requests:
https://argovis.colorado.edu/selection/profiles?startDate=2020-05-25&endDate=2020-06-25&shape=[[[-70,20],[-70,30],[-60,30],[-60,20],[-70,20]]]&presRange=[0,100]
Why is the "DIRECTION" not returned ?
May be one direction "A" is selected in your database, in this case then, we can add this field internally within argopy at fetch time so that the xarray methods will work

**Comment by tylertucker202** [comment]
>     * **argovis** fetching works for `float`, `profile` and `region`. Region fetching doesn't return the DIRECTION variable though. That makes `ds.argo.point2profile()` failed
> 
> 
> I think this is coming from Argovis response,
> @tylertucker202 , for this kind of requests:
> [https://argovis.colorado.edu/selection/profiles?startDate=2020-05-25&endDate=2020-06-25&shape=[[[-70,20],[-70,30],[-60,30],[-60,20],[-70,20]]]&presRange=[0,100]](https://argovis.colorado.edu/selection/profiles?startDate=2020-05-25&endDate=2020-06-25&shape=%5B%5B%5B-70,20%5D,%5B-70,30%5D,%5B-60,30%5D,%5B-60,20%5D,%5B-70,20%5D%5D%5D&presRange=%5B0,100%5D)
> Why is the "DIRECTION" not returned ?
> May be one direction "A" is selected in your database, in this case then, we can add this field internally within argopy at fetch time so that the xarray methods will work

Direction has been included in the selection API. Thanks for spotting the bug.

**Comment by quai20** [comment]
> Direction has been included in the selection API. Thanks for spotting the bug.
My pleasure :monocle_face:

**Comment by gmaze** [comment]
>     * **argovis** fetching works for `float`, `profile` and `region`. Region fetching doesn't return the DIRECTION variable though. That makes `ds.argo.point2profile()` failed
> 
> 
> I think this is coming from Argovis response,
> @tylertucker202 , for this kind of requests:
> [https://argovis.colorado.edu/selection/profiles?startDate=2020-05-25&endDate=2020-06-25&shape=[[[-70,20],[-70,30],[-60,30],[-60,20],[-70,20]]]&presRange=[0,100]](https://argovis.colorado.edu/selection/profiles?startDate=2020-05-25&endDate=2020-06-25&shape=%5B%5B%5B-70,20%5D,%5B-70,30%5D,%5B-60,30%5D,%5B-60,20%5D,%5B-70,20%5D%5D%5D&presRange=%5B0,100%5D)
> Why is the "DIRECTION" not returned ?
> May be one direction "A" is selected in your database, in this case then, we can add this field internally within argopy at fetch time so that the xarray methods will work

That means that we also need to include this pattern in testings

**Pull request merged**
