### PR TITLE
API to create source file and data for OWC software

### LINKED ISSUE #141: Method to create float_source/<WMO>.mat file for OWC
## Rational for this new feature
[Matlab](https://github.com/ArgoDMQC/matlab_owc) and [python](https://github.com/euroargodev/argodmqc_owc) implementations of the Argo salinity calibration method OWC take as data input a preprocessed version of Argo profile measurements.
This preprocessing is [not implemented in pyowc yet](https://github.com/euroargodev/argodmqc_owc/issues/33), and is [done here in matlab](https://github.com/euroargodev/dm_floats/blob/master/src/ow_source/create_float_source.m).
**Argopy should be able to provide this set of preprocessed data for expert users**.
This has been discussed in here euroargodev/argodmqc_owc/issues/33 and here euroargodev/DMQC-PCM/issues/21.

## API design
First we would fetch float data to QC:
```python
loader = ArgoDataFetcher(mode='expert').float(6902746)
ds = loader.load().data
```
Then, we could have 2 methods accessible with the argopy ``argo`` accessor:
1. a method to preprocessed the data and return a new xarray dataset, to be used by python softwares (eg: pyowc)
2. a method to save these preprocessed data in Matlab files that could directly be used by the Matlab OWC software or the current implementation of pyowc.

This could go like this:
```python
# Preprocessed data for OWC:
ds_processed = ds.argo.to_owc()
```
and then possibly create matlab files to be used by OWC softwares:
```python
dest = os.path.sep.join(["/", "float_source", "%i.mat" % wmo])
mat_data_file_list = ds.argo.create_float_source(dest)
```
The former method would ran internally ``ds.argo.to_owc()`` and then save Matlab files.

## List of tasks for the ``to_owc`` method:
Based on what is done by [the matlab function](https://github.com/euroargodev/dm_floats/blob/master/src/ow_source/create_float_source.m), the argopy method should do:

- [x] fetch netcdf data in expert mode 
- [x] recalculates salinity from the adjusted pressure if necessary.
- [x] calculates potential temperature
- [x] converts dates (juld> year with decimals)
- [x] converts longitudes
- [x] harmonizes QC (pres, temp, psal), excludes outliers
- [x] sub-sample data along 10db pressure bins
- [x] ensures that data that are at about the same pressure have the same vertical index for all cycles (which is not necessarily the case if there are changes in resolution from one cycle to the other, incomplete profiles ...)

### PR DESCRIPTION
**Pull request by gmaze**
This will close #141 

Documentation of the new API:

https://argopy.readthedocs.io/en/mat-owc/data_quality_control.html#salinity-calibration

### CODE REVIEW

**Comment by gmaze** [comment]
Examples for the validation are given here: https://github.com/euroargodev/argopy/issues/141#issuecomment-964891193

**Comment by gmaze** [comment]
Contemplating at fixing #155 also

**Comment by kamwal** [comment]
Hi @gmaze, Thank you for pinning me. 
I will look at/test your core around tomorrow if that's fine.

**Comment by kamwal** [comment]
I have started some reviewing process of this code.
Initially the installation and the first run of the code went without any problems.
I need to continue the further code checks (comparisons with matlab code output from the create_float_source) and better understand all the steps undertaken in the code.

@gmaze, are you expecting from me to test the code or rather peer review. I don't have much experience in peer review and it can take a wile for me now.

**Comment by gmaze** [comment]
@kamwal 
Thanks for looking at this
The review I expect, and sorry I should have been more precise earlier, is:
- check that you can make the API to run as expected (never know what you get if not ran from my own dev env, despite all CI)
- perform some comparisons with the Matlab output, I've made a lot, but never sure enough, please take into consideration that the Matlab routine is not perfect and misses some points at the bottom of the profile, which I think we don't miss. See #141  discussion

Poking you with a review, is also a nice way to simply let you know what we've done in here !

**Comment by gmaze** [comment]
@kamwal , looking at the code details is clearly not expected, please review as an "end user" rather "code dev" :
- does it work as expected ?
- is the doc enough: 
  - https://argopy.readthedocs.io/en/mat-owc/data_quality_control.html#salinity-calibration
  - https://argopy.readthedocs.io/en/mat-owc/generated/xarray.Dataset.argo.create_float_source.html

thanks !

**Review by quai20 — APPROVED** [review]

**Comment by gmaze** [comment]
Thanks @quai20 and @kamwal for your review !

**Pull request merged**
