### PR TITLE
web API status

### PR DESCRIPTION
**Pull request by gmaze**
Following discussion in #35 

Play with web API status (for erddap and argovis)

Add badges for API status

### CODE REVIEW

**Comment by gmaze** [comment]
Hi all,
I propose here a simple new function available of the package level as: ``argopy.status()``

In a notebook, this function will insert badges indicating the current status (availability) of web API like this:

Screenshot 2020-09-28 at 18 38 47

and if not in a notebook, it will print something like:
```python
erddap: up
argovis: up
```

**Comment by gmaze** [comment]
As a complement I also created the new repo https://github.com/euroargodev/argopy-status that is dedicated to create online monitoring tools of what we need in argopy.

You can also check and subscribe to monitoring results at https://argopy.statuspage.io

**Comment by gmaze** [comment]
>  I propose here a simple new function available of the package level as: `argopy.status()`

What would be great, would be to have an asynchronous check of the status that would run in the background once the function is called. So that the status could be replaced and update in the same cell.

But I don't know how to do this

**Comment by gmaze** [comment]
> But I don't know how to do this

I tried to be a quick learner on this one !

So I implemented a new version of ``argopy.status()`` that will refresh automatically.
It has a default refresh rate of 1 sec, this can be tuned with the option ``argopy.status(refresh=10)``

I also included a status check for the local ftp data source, in case the ftp folder would be "unplugged" after the option was set.

Example of output:

All online:
Screenshot 2020-09-29 at 00 33 29

After going offline:
Screenshot 2020-09-29 at 00 33 10

**Comment by gmaze** [comment]
Note that this is not yet very robust wrt to environment, i.e. running in a notebook cell or ipython/python terminal

**Comment by quai20** [comment]
Strange behaviour in my jupyter-lab, not rendering the argopy.status() but does render ipywidgets examples.

Capture du 2020-10-06 11-30-19

**Comment by gmaze** [comment]
for some unknown reasons I had the same issue, no rendering of the html out of argopy.status(),
but I could not reproduced the issue !

**Comment by gmaze** [comment]
@quai20 did you identified what was going on with the status rendering in your notebooks ?

**Comment by quai20** [comment]
> @quai20 did you identified what was going on with the status rendering in your notebooks ?

After a clean reinstall of **ipywidgets** and the modification you did in [
ef99ed1](https://github.com/euroargodev/argopy/pull/36/commits/ef99ed182870e6f0bc82e331aedf5e4008599336), it works well in my environment (both lab & notebooks).

**Review by quai20 — APPROVED** [review]

**Pull request merged**
