### PR TITLE
Xarray backend to open Argo Netcdf files

### LINKED ISSUE #176: Xarray backend to open Argo Netcdf file formats
When openning an Argo netcdf file with xarray, most of the variables are not decoded properly and returned as objects.
As shown in the exemple below, 48 out of 64 data variables are not decoded as they should.

So should we implement a new xarray backend to fix this ?

The added value would be that:
- users could use argopy to open files directly, as they want
- argopy machinery would be cleaner if decoding would be done in a single place

## Proposition
Register a new xarray backend for Argo Netcdf files:
```python
import xarray as xr
ds = xr.open_dataset("/Users/gmaze/data/ARGO/ftp_current/dac/aoml/1901393/1901393_prof.nc", engine='argo')
```

To implement this: https://xarray.pydata.org/en/stable/internals/how-to-add-new-backend.html

Since Argopy has already all the necessary snippets implemented in various places, this could easily be packaged I guess.

## The problem
Even with classic decoder options turned on, xarray cannot understand Argo variable type:
```python
import xarray as xr
ds = xr.open_dataset("/Users/gmaze/data/ARGO/ftp_current/dac/aoml/1901393/1901393_prof.nc", 
                     decode_cf=1, use_cftime=1, mask_and_scale=1,)
for v in ds.data_vars:
    print("%30s: %s" % (v, ds[v].data.dtype))
```

```python
                     DATA_TYPE: object
                FORMAT_VERSION: object
              HANDBOOK_VERSION: object
           REFERENCE_DATE_TIME: object
                 DATE_CREATION: object
                   DATE_UPDATE: object
               PLATFORM_NUMBER: object
                  PROJECT_NAME: object
                       PI_NAME: object
            STATION_PARAMETERS: object
                  CYCLE_NUMBER: float64
                     DIRECTION: object
                   DATA_CENTRE: object
                  DC_REFERENCE: object
          DATA_STATE_INDICATOR: object
                     DATA_MODE: object
                 PLATFORM_TYPE: object
               FLOAT_SERIAL_NO: object
              FIRMWARE_VERSION: object
                 WMO_INST_TYPE: object
                          JULD: object
                       JULD_QC: object
                 JULD_LOCATION: object
                      LATITUDE: float64
                     LONGITUDE: float64
                   POSITION_QC: object
            POSITIONING_SYSTEM: object
               PROFILE_PRES_QC: object
               PROFILE_TEMP_QC: object
               PROFILE_PSAL_QC: object
      VERTICAL_SAMPLING_SCHEME: object
         CONFIG_MISSION_NUMBER: float64
                          PRES: float32
                       PRES_QC: object
                 PRES_ADJUSTED: float32
              PRES_ADJUSTED_QC: object
           PRES_ADJUSTED_ERROR: float32
                          TEMP: float32
                       TEMP_QC: object
                 TEMP_ADJUSTED: float32
              TEMP_ADJUSTED_QC: object
           TEMP_ADJUSTED_ERROR: float32
                          PSAL: float32
                       PSAL_QC: object
                 PSAL_ADJUSTED: float32
              PSAL_ADJUSTED_QC: object
           PSAL_ADJUSTED_ERROR: float32
                     PARAMETER: object
     SCIENTIFIC_CALIB_EQUATION: object
  SCIENTIFIC_CALIB_COEFFICIENT: object
      SCIENTIFIC_CALIB_COMMENT: object
         SCIENTIFIC_CALIB_DATE: object
           HISTORY_INSTITUTION: object
                  HISTORY_STEP: object
              HISTORY_SOFTWARE: object
      HISTORY_SOFTWARE_RELEASE: object
             HISTORY_REFERENCE: object
                  HISTORY_DATE: object
                HISTORY_ACTION: object
             HISTORY_PARAMETER: object
            HISTORY_START_PRES: float32
             HISTORY_STOP_PRES: float32
        HISTORY_PREVIOUS_VALUE: float32
                HISTORY_QCTEST: object
```

### PR DESCRIPTION
**Pull request by gmaze**
Close #176 

When openning an Argo netcdf file with xarray, most of the variables are not decoded properly and returned as objects.
For a regular core-Argo profile file, 48 out of 64 data variables are not decoded as they should.

This PR tries to implement a new Xarray backend to open Argo Netcdf files where all the variables will be "casted" correctly.

We should be able to open *any* of the reference Argo netcdf files:
- [x] Core-Argo individual profile files (<R/D><FloatWmoID>_<XXX><D>.nc). The core-Argo profile files contain the core parameters provided by a float: pressure, temperature, salinity, conductivity (PRES, TEMP, PSAL, CNDC).
- [x] B-Argo individual profile file (B<R/D><FloatWmoID>_<XXX><D>.nc). A B-Argo profile file contains all the parameters from a float, except the core-Argo parameters temperature, salinity, conductivity (TEMP, PSAL, CNDC). A float that performs only CTD measurements does not have B-Argo data files.
- [x] BGC-Argo individual synthetic profile file (M<R/D><FloatWmoID>_<XXX><D>.nc). The synthetic file contains the core-Argo and BGC-Argo parameters listed on reference table 3. The intermediate parameters are ignored by the synthetic files.
- [x] Argo trajectory data file (<FloatWmoID>_<R/D>traj.nc). The Argo trajectory files contain the core and BGC parameters provided by a float.
- [x] Metadata file (<FloatWmoID>_meta.nc).
- [x] Technical Data file (<FloatWmoID>_tech.nc).

And obviously:
- [x] Core-Argo multiple profile files

### CODE REVIEW

**Comment by gmaze** [comment]
I tested the 'argo' engine on a collection of sample files covering all of 7 Argo data types, and it works !

```
OK for              Argo profile (test file: /dac/bodc/6901929/6901929_prof.nc)
OK for              Argo profile (test file: /dac/meds/4901079/profiles/D4901079_110.nc)
OK for              Argo profile (test file: /dac/aoml/13857/profiles/R13857_001.nc)
OK for           Argo trajectory (test file: /dac/aoml/5900446/5900446_Dtraj.nc)
OK for           Argo trajectory (test file: /dac/csio/2902696/2902696_Rtraj.nc)
OK for    Argo synthetic profile (test file: /dac/coriolis/3902131/3902131_Sprof.nc)
OK for    Argo synthetic profile (test file: /dac/coriolis/3902131/profiles/SD3902131_001.nc)
OK for    Argo synthetic profile (test file: /dac/coriolis/3902131/profiles/SD3902131_001D.nc)
OK for    Argo synthetic profile (test file: /dac/coriolis/6903247/profiles/SR6903247_134.nc)
OK for    Argo synthetic profile (test file: /dac/coriolis/6903247/profiles/SR6903247_134D.nc)
OK for            B-Argo profile (test file: /dac/coriolis/3902131/profiles/BR3902131_001.nc)
OK for            B-Argo profile (test file: /dac/coriolis/3902131/profiles/BR3902131_001D.nc)
OK for         B-Argo trajectory (test file: /dac/coriolis/3902131/3902131_BRtraj.nc)
OK for         B-Argo trajectory (test file: /dac/coriolis/6903247/6903247_BRtraj.nc)
OK for       Argo technical data (test file: /dac/incois/2902269/2902269_tech.nc)
OK for       Argo technical data (test file: /dac/nmdis/2901623/2901623_tech.nc)
OK for            Argo meta-data (test file: /dac/jma/4902252/4902252_meta.nc)
OK for            Argo meta-data (test file: /dac/coriolis/1900857/1900857_meta.nc)
```

The API is quite simple !
```python
ds = xr.open_dataset(file, engine='argo')
```
then I check if 100% of the variables are casted (as string, int, float or datetime) and none is returned as an "object".

**Comment by quai20** [comment]
"requests" module is missing from requirements when installing from scratch.

**Comment by quai20** [comment]
Warning when casting datetime : 
```
argopy/xarray.py:150: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be relaxed in xarray, as it is an artifact from pandas which is now beginning to support non-nanosecond precision values. This warning is caused by passing non-nanosecond np.datetime64 or np.timedelta64 values to the DataArray or Variable constructor; it can be silenced by converting the values to nanosecond precision ahead of time.
  da = da.astype(type)
```

**Review by quai20 — APPROVED** [review]
minor comments about "requests" module & `datetime` cast warning.

**Comment by gmaze** [comment]
> Warning when casting datetime

Could you please give me the output of:

```python
argopy.show_versions()
```

**Comment by quai20** [comment]
> > Warning when casting datetime
> 
> Could you please give me the output of:
> 
> ```python
> argopy.show_versions()
> ```

```
SYSTEM
------
commit: None
python: 3.9.16 (main, Mar  8 2023, 14:00:05) 
[GCC 11.2.0]
python-bits: 64
OS: Linux
OS-release: 4.15.0-211-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: fr_FR.UTF-8
LOCALE: fr_FR.UTF-8
libhdf5: 1.12.2
libnetcdf: 4.9.1

INSTALLED VERSIONS: CORE
------------------------
aiohttp     : 3.8.4       
argopy      : 0.1.13      
erddapy     : 2.0.1       
fsspec      : 2023.5.0    
netCDF4     : 1.6.3       
packaging   : 23.1        
scipy       : 1.10.1      
toolz       : 0.12.0      
xarray      : 2023.5.0    

INSTALLED VERSIONS: EXT.UTIL
----------------------------
gsw         : -           
tqdm        : -           
zarr        : -           

INSTALLED VERSIONS: EXT.PERF
----------------------------
dask        : -           
distributed : -           
pyarrow     : -           

INSTALLED VERSIONS: EXT.PLOT
----------------------------
IPython     : 8.13.2      
cartopy     : -           
ipykernel   : 6.23.1      
ipywidgets  : -           
matplotlib  : -           
seaborn     : -           

INSTALLED VERSIONS: DEV
-----------------------
black       : -           
bottleneck  : -           
cfgrib      : -           
cftime      : 1.6.2       
conda       : -           
flake8      : -           
nc_time_axis: -           
numpy       : 1.24.3      
pandas      : 2.0.1       
pip         : 23.0.1      
pytest      : -           
pytest_cov  : -           
pytest_env  : -           
pytest_localftpserver: -           
setuptools  : 66.0.0      
sphinx      : -           
```

**Comment by gmaze** [comment]
ok, the warning comes from the latest Pandas 2.0 that raises a lot of new warnings
I'll fix this in another PR

**Pull request merged**
